:- module(disjointtypes, [transition/2]).
transition(0,[dynamic,static]).
transition(1,[dynamic,static]).
transition('$VAR',[dynamic,var]).
transition([dynamic]*[dynamic],[dynamic]).
transition([dynamic]*[dynamic,static],[dynamic]).
transition([dynamic]*[dynamic,var],[dynamic]).
transition([dynamic,static]*[dynamic],[dynamic]).
transition([dynamic,static]*[dynamic,static],[dynamic,static]).
transition([dynamic,static]*[dynamic,var],[dynamic]).
transition([dynamic,var]*[dynamic],[dynamic]).
transition([dynamic,var]*[dynamic,static],[dynamic]).
transition([dynamic,var]*[dynamic,var],[dynamic]).
transition([dynamic]+[dynamic],[dynamic]).
transition([dynamic]+[dynamic,static],[dynamic]).
transition([dynamic]+[dynamic,var],[dynamic]).
transition([dynamic,static]+[dynamic],[dynamic]).
transition([dynamic,static]+[dynamic,static],[dynamic,static]).
transition([dynamic,static]+[dynamic,var],[dynamic]).
transition([dynamic,var]+[dynamic],[dynamic]).
transition([dynamic,var]+[dynamic,static],[dynamic]).
transition([dynamic,var]+[dynamic,var],[dynamic]).
transition([dynamic]-[dynamic],[dynamic]).
transition([dynamic]-[dynamic,static],[dynamic]).
transition([dynamic]-[dynamic,var],[dynamic]).
transition([dynamic,static]-[dynamic],[dynamic]).
transition([dynamic,static]-[dynamic,static],[dynamic,static]).
transition([dynamic,static]-[dynamic,var],[dynamic]).
transition([dynamic,var]-[dynamic],[dynamic]).
transition([dynamic,var]-[dynamic,static],[dynamic]).
transition([dynamic,var]-[dynamic,var],[dynamic]).
transition([[dynamic],dynamic],[dynamic]).
transition([[dynamic],dynamic,static],[dynamic]).
transition([[dynamic],dynamic,var],[dynamic]).
transition([[dynamic,static],dynamic],[dynamic]).
transition([[dynamic,static],dynamic,static],[dynamic,static]).
transition([[dynamic,static],dynamic,var],[dynamic]).
transition([[dynamic,var],dynamic],[dynamic]).
transition([[dynamic,var],dynamic,static],[dynamic]).
transition([[dynamic,var],dynamic,var],[dynamic]).
transition([],[dynamic,static]).
