# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded pkgLogenDialog 1.0 [list source [file join $dir pkgLogenDialog.tcl]]
package ifneeded pkgLogenMenu 1.0 [list source [file join $dir pkgLogenMenu.tcl]]
package ifneeded pkgLogenParser 1.0 [list source [file join $dir pkgLogenParser.tcl]]
package ifneeded pkgLogenToolbar 1.0 [list source [file join $dir pkgLogenToolbar.tcl]]
package ifneeded pkgProlog 1.0 [list source [file join $dir pkgProlog.tcl]]
