/*  Generated by CHR bootstrap compiler
    From: fib.pl
    Date: Wed Mar  8 11:50:51 2006

    DO NOT EDIT.  EDIT THE CHR FILE INSTEAD
*/
:-use_module(chr_runtime).
:-style_check(-singleton).
:-style_check(- (discontiguous)).
:-use_module(library(chr)).
go :-
	statistics(runtime, [A|B]),
	fib(17, C),
	write(fib(17)=C),
	nl,
	statistics(runtime, [D|E]),
	F is D-A,
	write(F).
:-use_module(chr(chr_runtime)).
:-use_module(chr(chr_hashtable_store)).
:-use_module(library('clp/clp_events')).
activate_constraint(A, B, C, D) :-
	arg(2, C, E),
	'chr get_mutable'(F, E),
	'chr update_mutable'(active, E),
	(   nonvar(D)
	->  true
	;   arg(4, C, G),
	    'chr get_mutable'(H, G),
	    D is H+1,
	    'chr update_mutable'(D, G)
	),
	(   compound(F)
	->  term_variables(F, B),
	    'chr none_locked'(B),
	    A=yes
	;   F==removed
	->  chr_indexed_variables(C, B),
	    A=yes
	;   B=[],
	    A=no
	).
allocate_constraint(A, B, C, D) :-
	B=..[suspension, E, F, A, G, H, C|D],
	'chr create_mutable'(0, G),
	'chr empty_history'(I),
	'chr create_mutable'(I, H),
	chr_indexed_variables(B, J),
	'chr create_mutable'(passive(J), F),
	'chr gen_id'(E).
chr_indexed_variables(A, []).
'$insert_in_store_fib/2'(A) :-
	true,
	arg(7, A, B),
	nb_getval('$chr_store_multi_hash_user:fib/2-1', C),
	insert_ht(C, B, A),
	true.
'$delete_from_store_fib/2'(A) :-
	true,
	arg(7, A, B),
	nb_getval('$chr_store_multi_hash_user:fib/2-1', C),
	delete_ht(C, B, A),
	true.
'$enumerate_suspensions'(A) :-
	nb_getval('$chr_store_multi_hash_user:fib/2-1', B),
	value_ht(B, A).
'$via1_multi_hash_fib/2-1'(A, B) :-
	nb_getval('$chr_store_multi_hash_user:fib/2-1', C),
	lookup_ht(C, A, B).
'$chr_initialization' :-
	new_ht(A),
	nb_setval('$chr_store_multi_hash_user:fib/2-1', A),
	true.
:-'$chr_initialization'.
:-dynamic user:exception/3.
:-multifile user:exception/3.
user:exception(undefined_global_variable, A, retry) :-
	'$chr_prolog_global_variable'(A),
	'$chr_initialization'.
'$chr_prolog_global_variable'('$chr_store_multi_hash_user:fib/2-1').
fib(A, B) :-
	'fib/2__0'(A, B, C).
'fib/2__0'(A, B, C) :-
	'$via1_multi_hash_fib/2-1'(A, D),
	'chr sbag_member'(E, D),
	E=suspension(F, G, H, I, J, K, L, M),
	G=mutable(active), !,
	M=B.
'fib/2__0'(0, A, B) :-
	allocate_constraint(true, B, fib(0, A), [0, A]), !,
	activate_constraint(C, D, B, E),
	(   C==yes
	->  '$insert_in_store_fib/2'(B)
	;   true
	),
	A=1,
	(   B=suspension(F, G, H, I, J, K, L, M),
	    G=mutable(active),
	    I=mutable(E)
	->  'chr update_mutable'(inactive, G),
	    'fib/2__1'(0, A, B)
	;   true
	).
'fib/2__0'(A, B, C) :-
	allocate_constraint(true, C, fib(A, B), [A, B]),
	'fib/2__1'(A, B, C).
'fib/2__1'(1, A, B) :- !,
	activate_constraint(C, D, B, E),
	(   C==yes
	->  '$insert_in_store_fib/2'(B)
	;   true
	),
	A=1,
	(   B=suspension(F, G, H, I, J, K, L, M),
	    G=mutable(active),
	    I=mutable(E)
	->  'chr update_mutable'(inactive, G),
	    'fib/2__2'(1, A, B)
	;   true
	).
'fib/2__1'(A, B, C) :-
	'fib/2__2'(A, B, C).
'fib/2__2'(A, B, C) :-
	A>1, !,
	activate_constraint(D, E, C, F),
	(   D==yes
	->  '$insert_in_store_fib/2'(C)
	;   true
	),
	G is A-1,
	fib(G, H),
	I is A-2,
	fib(I, J),
	B is H+J,
	(   C=suspension(K, L, M, N, O, P, Q, R),
	    L=mutable(active),
	    N=mutable(F)
	->  'chr update_mutable'(inactive, L),
	    'fib/2__3'(A, B, C)
	;   true
	).
'fib/2__2'(A, B, C) :-
	'fib/2__3'(A, B, C).
'fib/2__3'(A, B, C) :-
	activate_constraint(D, E, C, F),
	(   D==yes
	->  '$insert_in_store_fib/2'(C)
	;   true
	).
:-multifile chr:'$chr_module'/1.
chr:'$chr_module'(user).
end_of_file.
