'denotes_$VAR'(f).
'denotes_a'(g).
'denotes_.'(g,glist,glist).
'denotes_.'(glist,glist,glist).
'denotes_.'(g,flist,ilist).
'denotes_.'(g,i,i).
'denotes_.'(f,g,i).
'denotes_.'(f,f,i).
'denotes_.'(f,i,i).
'denotes_.'(i,g,i).
'denotes_.'(i,f,i).
'denotes_.'(i,i,i).
'denotes_[]'(g).
