le(g,g):-true.
lt(g,g):-true.
ge(g,g):-true.
gt(g,g):-true.
exprEval(g,g):-true.
ident(A,B):-true.
nonident(A,B):-true.
cut:-true.
eq(g,g):-true.
noteq(g,g):-true.
termlt(A,B):-true.
termle(A,B):-true.
termgt(A,B):-true.
termge(A,B):-true.
notequal(A,B):-true.
univ(g,g):-true.
univ(ng,ng):-true.
compound(A):-true.
display(A):-true.
listing:-true.
listing(A):-true.
nl:-true.
nonvar(A):-true.
print(A):-true.
portray_clause(A):-true.
read(A):-true.
repeat:-true.
true:-true.
var(A):-true.
write(A):-true.
writeq(A):-true.
atom(g):-true.
atomic(g):-true.
compare(g,A,B):-true.
float(g):-true.
ground(g):-true.
integer(g):-true.
number(g):-true.
length(A,g):-true.
statistics(g,g):-true.
keysort(g,g):-true.
keysort(ng,ng):-true.
sort(ng,ng):-true.
tab(g):-true.
put(g):-true.
arg(g,g,g):-true.
arg(g,ng,g):-true.
arg(g,ng,ng):-true.
name(g,g):-true.
functor(A,g,g):-true.
neg(A):-true.
le_error(ng,A):-true.
le_error(A,ng):-true.
lt_error(ng,A):-true.
lt_error(A,ng):-true.
ge_error(ng,A):-true.
ge_error(A,ng):-true.
gt_error(ng,A):-true.
gt_error(A,ng):-true.
exprEval_error(ng,A):-true.
exprEval_error(A,ng):-true.
eq_error(ng,A):-true.
eq_error(A,ng):-true.
noteq_error(ng,A):-true.
noteq_error(A,ng):-true.
univ_error(ng,ng):-true.
keysort_error(ng,A):-true.
sort_error(ng,A):-true.
tab_error(ng):-true.
put_error(ng):-true.
arg_error(ng,A,B):-true.
arg_error(A,ng,B):-true.
name_error(ng,ng):-true.
functor_error(ng,g,ng):-true.
functor_error(ng,ng,A):-true.
denotes_what(g).
denotes_rivers(g).
denotes_are(g).
denotes_there(g).
'denotes_?'(g).
'denotes_[]'(g).
'denotes_.'(A,ng,ng).
'denotes_.'(ng,A,ng).
'denotes_.'(g,g,g).
denotes_does(g).
denotes_afghanistan(g).
denotes_border(g).
denotes_china(g).
denotes_is(g).
denotes_the(g).
denotes_capital(g).
denotes_of(g).
denotes_upper_volta(g).
denotes_where(g).
denotes_largest(g).
denotes_country(g).
denotes_which(g).
'denotes_`'(g).
denotes_s(g).
denotes_london(g).
denotes_countries(g).
denotes_european(g).
denotes_how(g).
denotes_large(g).
denotes_smallest(g).
denotes_american(g).
denotes_ocean(g).
denotes_that(g).
denotes_borders(g).
denotes_african(g).
denotes_and(g).
denotes_asian(g).
denotes_capitals(g).
denotes_bordering(g).
denotes_baltic(g).
denotes_bordered(g).
denotes_by(g).
denotes_two(g).
denotes_seas(g).
denotes_many(g).
denotes_danube(g).
denotes_flow(g).
denotes_through(g).
denotes_total(g).
denotes_area(g).
denotes_south(g).
denotes_equator(g).
denotes_not(g).
denotes_in(g).
denotes_australasia(g).
denotes_average(g).
denotes_each(g).
denotes_continent(g).
denotes_more(g).
denotes_than(g).
denotes_one(g).
denotes_some(g).
denotes_any(g).
denotes_from(g).
denotes_a(g).
denotes_river(g).
denotes_flows(g).
denotes_into(g).
denotes_black_sea(g).
denotes_terminal(g).
denotes_x(A,B,C,ng,ng).
denotes_x(A,B,ng,C,ng).
denotes_x(A,ng,B,C,ng).
denotes_x(ng,A,B,C,ng).
denotes_x(g,g,g,g,g).
denotes_gap(g).
denotes_nonterminal(g).
denotes_1(g).
'denotes_#'(A,B,C,ng,ng).
'denotes_#'(A,B,ng,C,ng).
'denotes_#'(A,ng,B,C,ng).
'denotes_#'(ng,A,B,C,ng).
'denotes_#'(g,g,g,g,g).
denotes_0(g).
denotes_subj(g).
'denotes_#'(A,B,ng,ng).
'denotes_#'(A,ng,B,ng).
'denotes_#'(ng,A,B,ng).
'denotes_#'(g,g,g,g).
denotes_compl(g).
denotes_undef(g).
denotes_main(g).
denotes_aux(g).
denotes_decl(g).
denotes_nil(g).
'denotes_.'(g).
'denotes_!'(g).
denotes_pp(A,B,C,ng,ng).
denotes_pp(A,B,ng,C,ng).
denotes_pp(A,ng,B,C,ng).
denotes_pp(ng,A,B,C,ng).
denotes_pp(g,g,g,g,g).
denotes_pp(A,ng,ng).
denotes_pp(ng,A,ng).
denotes_pp(g,g,g).
'denotes_,'(g).
denotes_decl(ng,ng).
denotes_decl(g,g).
denotes_whq(A,ng,ng).
denotes_whq(ng,A,ng).
denotes_whq(g,g,g).
denotes_np(A,B,C,D,E,F,ng,ng).
denotes_np(A,B,C,D,E,ng,F,ng).
denotes_np(A,B,C,D,ng,E,F,ng).
denotes_np(A,B,C,ng,D,E,F,ng).
denotes_np(A,B,ng,C,D,E,F,ng).
denotes_np(A,ng,B,C,D,E,F,ng).
denotes_np(ng,A,B,C,D,E,F,ng).
denotes_np(g,g,g,g,g,g,g,g).
denotes_np(A,B,ng,ng).
denotes_np(A,ng,B,ng).
denotes_np(ng,A,B,ng).
denotes_np(g,g,g,g).
denotes_def(g).
'denotes_+'(A,ng,ng).
'denotes_+'(ng,A,ng).
'denotes_+'(g,g,g).
denotes_part(A,ng,ng).
denotes_part(ng,A,ng).
denotes_part(g,g,g).
denotes_3(g).
denotes_indef(g).
denotes_plu(g).
denotes_int_det(ng,ng).
denotes_int_det(g,g).
denotes_np_head(A,B,ng,ng).
denotes_np_head(A,ng,B,ng).
denotes_np_head(ng,A,B,ng).
denotes_np_head(g,g,g,g).
denotes_adv_phrase(A,B,ng,ng).
denotes_adv_phrase(A,ng,B,ng).
denotes_adv_phrase(ng,A,B,ng).
denotes_adv_phrase(g,g,g,g).
denotes_adj(g).
denotes_wh(ng,ng).
denotes_wh(g,g).
denotes_value(A,ng,ng).
denotes_value(ng,A,ng).
denotes_value(g,g,g).
denotes_predicate(A,B,ng,ng).
denotes_predicate(A,ng,B,ng).
denotes_predicate(ng,A,B,ng).
denotes_predicate(g,g,g,g).
denotes_quant(g).
denotes_prep(ng,ng).
denotes_prep(g,g).
denotes_neg(g).
denotes_gen_marker(g).
denotes_nogap(g).
denotes_proper(g).
denotes_np_head0(A,B,ng,ng).
denotes_np_head0(A,ng,B,ng).
denotes_np_head0(ng,A,B,ng).
denotes_np_head0(g,g,g,g).
denotes_whose(g).
denotes_det(A,B,ng,ng).
denotes_det(A,ng,B,ng).
denotes_det(ng,A,B,ng).
denotes_det(g,g,g,g).
denotes_det(ng,ng).
denotes_det(g,g).
denotes_generic(g).
denotes_q(ng,ng).
denotes_q(g,g).
denotes_verb_form(A,B,C,ng,ng).
denotes_verb_form(A,B,ng,C,ng).
denotes_verb_form(A,ng,B,C,ng).
denotes_verb_form(ng,A,B,C,ng).
denotes_verb_form(g,g,g,g,g).
denotes_neg(A,ng,ng).
denotes_neg(ng,A,ng).
denotes_neg(g,g,g).
denotes_pos(g).
denotes_imp(ng,ng).
denotes_imp(g,g).
denotes_you(g).
denotes_imp(g).
denotes_fin(g).
denotes_2(g).
denotes_sin(g).
denotes_inf(g).
denotes_s(A,B,C,ng,ng).
denotes_s(A,B,ng,C,ng).
denotes_s(A,ng,B,C,ng).
denotes_s(ng,A,B,C,ng).
denotes_s(g,g,g,g,g).
denotes_be(g).
denotes_name(ng,ng).
denotes_name(g,g).
denotes_common(g).
denotes_poss(g).
denotes_quant(A,ng,ng).
denotes_quant(ng,A,ng).
denotes_quant(g,g,g).
denotes_at(g).
denotes_same(g).
'denotes_+'(ng,ng).
'denotes_+'(g,g).
denotes_not(ng,ng).
denotes_not(g,g).
denotes_least(g).
denotes_less(g).
denotes_most(g).
denotes_sup(A,ng,ng).
denotes_sup(ng,A,ng).
denotes_sup(g,g,g).
denotes_comp(A,B,ng,ng).
denotes_comp(A,ng,B,ng).
denotes_comp(ng,A,B,ng).
denotes_comp(g,g,g,g).
denotes_as(g).
denotes_rel(A,ng,ng).
denotes_rel(ng,A,ng).
denotes_rel(g,g,g).
denotes_reduced_rel(A,ng,ng).
denotes_reduced_rel(ng,A,ng).
denotes_reduced_rel(g,g,g).
denotes_pres(g).
denotes_verb(A,B,C,ng,ng).
denotes_verb(A,B,ng,C,ng).
denotes_verb(A,ng,B,C,ng).
denotes_verb(ng,A,B,C,ng).
denotes_verb(g,g,g,g,g).
denotes_verb(A,B,C,D,ng,ng).
denotes_verb(A,B,C,ng,D,ng).
denotes_verb(A,B,ng,C,D,ng).
denotes_verb(A,ng,B,C,D,ng).
denotes_verb(ng,A,B,C,D,ng).
denotes_verb(g,g,g,g,g,g).
denotes_have(g).
denotes_perf(g).
denotes_past(g).
denotes_part(g).
denotes_do(g).
denotes_active(g).
denotes_passive(g).
denotes_prog(g).
denotes_trans(g).
denotes_ditrans(g).
denotes_close(g).
denotes_dir(g).
denotes_arg(A,ng,ng).
denotes_arg(ng,A,ng).
denotes_arg(g,g,g).
denotes_np(g).
denotes_void(g).
denotes_predicate(g).
denotes_ind(g).
denotes_intrans(g).
denotes_conj(A,ng,ng).
denotes_conj(ng,A,ng).
denotes_conj(g,g,g).
denotes_conj(A,B,ng,ng).
denotes_conj(A,ng,B,ng).
denotes_conj(ng,A,B,ng).
denotes_conj(g,g,g,g).
denotes_adj(ng,ng).
denotes_adj(g,g).
denotes_adv(ng,ng).
denotes_adv(g,g).
denotes_pronoun(ng,ng).
denotes_pronoun(g,g).
denotes_place(g).
denotes_time(g).
denotes_when(g).
denotes_nb(ng,ng).
denotes_nb(g,g).
denotes_list(g).
denotes_end(g).
denotes_or(g).
denotes_who(g).
denotes_whom(g).
denotes_the(ng,ng).
denotes_the(g,g).
denotes_an(g).
denotes_every(g).
denotes_all(g).
denotes_no(g).
denotes_three(g).
denotes_four(g).
denotes_4(g).
denotes_five(g).
denotes_5(g).
denotes_six(g).
denotes_6(g).
denotes_seven(g).
denotes_7(g).
denotes_eight(g).
denotes_8(g).
denotes_nine(g).
denotes_9(g).
denotes_ten(g).
denotes_10(g).
denotes_everybody(g).
denotes_person(g).
denotes_everyone(g).
denotes_everything(g).
denotes_thing(g).
denotes_somebody(g).
denotes_someone(g).
denotes_something(g).
denotes_anybody(g).
denotes_anyone(g).
denotes_anything(g).
denotes_nobody(g).
denotes_nothing(g).
denotes_to(g).
denotes_with(g).
denotes_on(g).
denotes_proportion(g).
denotes_percentage(g).
denotes_contain(g).
denotes_drain(g).
denotes_exceed(g).
denotes_rise(g).
denotes_had(g).
denotes_contained(g).
denotes_drained(g).
denotes_exceeded(g).
denotes_flowed(g).
denotes_my(g).
denotes_your(g).
denotes_his(g).
denotes_masc(g).
denotes_her(g).
denotes_fem(g).
denotes_its(g).
denotes_neut(g).
denotes_our(g).
denotes_their(g).
denotes_i(g).
denotes_he(g).
denotes_she(g).
denotes_it(g).
denotes_we(g).
denotes_them(g).
denotes_me(g).
denotes_compl(ng,ng).
denotes_compl(g,g).
denotes_him(g).
denotes_us(g).
denotes_east(g).
denotes_eastof(g).
denotes_west(g).
denotes_westof(g).
denotes_north(g).
denotes_northof(g).
denotes_southof(g).
denotes_minimum(g).
denotes_restr(g).
denotes_maximum(g).
denotes_great(g).
denotes_big(g).
denotes_small(g).
denotes_old(g).
denotes_new(g).
denotes_populous(g).
denotes_greater(g).
denotes_bigger(g).
denotes_smaller(g).
denotes_larger(g).
denotes_older(g).
denotes_newer(g).
denotes_biggest(g).
denotes_oldest(g).
denotes_newest(g).
denotes_sum(g).
denotes_degree(g).
denotes_sqmile(g).
denotes_ksqmile(g).
denotes_thousand(g).
denotes_million(g).
denotes_city(g).
denotes_latitude(g).
denotes_longitude(g).
denotes_population(g).
denotes_region(g).
denotes_sea(g).
denotes_seamass(g).
denotes_number(g).
denotes_averages(g).
denotes_totals(g).
denotes_sums(g).
denotes_degrees(g).
denotes_sqmiles(g).
denotes_ksqmiles(g).
denotes_times(g).
denotes_places(g).
denotes_areas(g).
denotes_cities(g).
denotes_continents(g).
denotes_latitudes(g).
denotes_longitudes(g).
denotes_oceans(g).
denotes_persons(g).
denotes_people(g).
denotes_populations(g).
denotes_regions(g).
denotes_seamasses(g).
denotes_numbers(g).
denotes_am(g).
denotes_was(g).
denotes_were(g).
denotes_been(g).
denotes_being(g).
denotes_has(g).
denotes_having(g).
denotes_did(g).
denotes_doing(g).
denotes_done(g).
denotes_flowing(g).
denotes_rises(g).
denotes_rose(g).
denotes_risen(g).
denotes_contains(g).
denotes_containing(g).
denotes_drains(g).
denotes_draining(g).
denotes_exceeds(g).
denotes_exceeding(g).
denotes_yesterday(g).
denotes_tomorrow(g).
main:-chat_parser.
chat_parser:-string(A),determinate_say(A,B),fail.
chat_parser:-true.
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_[]'(K),'denotes_?'(J),denotes_there(H),denotes_are(F),denotes_rivers(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_[]'(K),'denotes_?'(J),denotes_china(H),denotes_border(F),denotes_afghanistan(D),denotes_does(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_[]'(O),'denotes_?'(N),denotes_upper_volta(L),denotes_of(J),denotes_capital(H),denotes_the(F),denotes_is(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_[]'(M),'denotes_?'(L),denotes_country(J),denotes_largest(H),denotes_the(F),denotes_is(D),denotes_where(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_[]'(Q),'denotes_?'(P),denotes_london(N),denotes_is(L),denotes_capital(J),denotes_s(H),'denotes_`'(F),denotes_country(D),denotes_which(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_[]'(K),'denotes_?'(J),denotes_european(H),denotes_are(F),denotes_countries(D),denotes_which(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_[]'(Q),'denotes_?'(P),denotes_country(N),denotes_american(L),denotes_smallest(J),denotes_the(H),denotes_is(F),denotes_large(D),denotes_how(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_.'(X,Y,W),'denotes_.'(Z,A1,Y),'denotes_.'(B1,C1,A1),'denotes_[]'(C1),'denotes_?'(B1),denotes_countries(Z),denotes_asian(X),denotes_borders(V),denotes_that(T),denotes_and(R),denotes_countries(P),denotes_african(N),denotes_borders(L),denotes_that(J),denotes_ocean(H),denotes_the(F),denotes_is(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_[]'(W),'denotes_?'(V),denotes_baltic(T),denotes_the(R),denotes_bordering(P),denotes_countries(N),denotes_the(L),denotes_of(J),denotes_capitals(H),denotes_the(F),denotes_are(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_[]'(Q),'denotes_?'(P),denotes_seas(N),denotes_two(L),denotes_by(J),denotes_bordered(H),denotes_are(F),denotes_countries(D),denotes_which(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_[]'(S),'denotes_?'(R),denotes_through(P),denotes_flow(N),denotes_danube(L),denotes_the(J),denotes_does(H),denotes_countries(F),denotes_many(D),denotes_how(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_.'(X,Y,W),'denotes_.'(Z,A1,Y),'denotes_.'(B1,C1,A1),'denotes_.'(D1,E1,C1),'denotes_.'(F1,G1,E1),'denotes_[]'(G1),'denotes_?'(F1),denotes_australasia(D1),denotes_in(B1),denotes_not(Z),denotes_and(X),denotes_equator(V),denotes_the(T),denotes_of(R),denotes_south(P),denotes_countries(N),denotes_of(L),denotes_area(J),denotes_total(H),denotes_the(F),denotes_is(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_.'(X,Y,W),'denotes_[]'(Y),'denotes_?'(X),denotes_continent(V),denotes_each(T),denotes_in(R),denotes_countries(P),denotes_the(N),denotes_of(L),denotes_area(J),denotes_average(H),denotes_the(F),denotes_is(D),denotes_what(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_[]'(U),'denotes_?'(T),denotes_continent(R),denotes_each(P),denotes_in(N),denotes_country(L),denotes_one(J),denotes_than(H),denotes_more(F),denotes_there(D),denotes_is(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_[]'(W),'denotes_?'(V),denotes_country(T),denotes_any(R),denotes_border(P),denotes_not(N),denotes_does(L),denotes_that(J),denotes_ocean(H),denotes_some(F),denotes_there(D),denotes_is(B).
string(A):-'denotes_.'(B,C,A),'denotes_.'(D,E,C),'denotes_.'(F,G,E),'denotes_.'(H,I,G),'denotes_.'(J,K,I),'denotes_.'(L,M,K),'denotes_.'(N,O,M),'denotes_.'(P,Q,O),'denotes_.'(R,S,Q),'denotes_.'(T,U,S),'denotes_.'(V,W,U),'denotes_.'(X,Y,W),'denotes_.'(Z,A1,Y),'denotes_[]'(A1),'denotes_?'(Z),denotes_black_sea(X),denotes_the(V),denotes_into(T),denotes_flows(R),denotes_river(P),denotes_a(N),denotes_which(L),denotes_from(J),denotes_countries(H),denotes_the(F),denotes_are(D),denotes_what(B).
determinate_say(A,B):-say(A,B),cut.
terminal(A,B,B,C,D):-denotes_x(E,F,A,D,C),denotes_terminal(F).
terminal(A,B,C,D,D):-gap(D),'denotes_.'(A,C,B).
gap(A):-denotes_x(B,C,D,E,A),denotes_gap(B).
gap(A):-'denotes_[]'(A).
virtual(A,B,C):-denotes_x(D,E,A,C,B),denotes_nonterminal(E).
is_pp(A):-'denotes_#'(B,C,D,E,A),denotes_1(B).
is_pred(A):-'denotes_#'(B,C,D,E,A),denotes_1(C).
is_trace(A):-'denotes_#'(B,C,D,E,A),denotes_1(D).
is_adv(A):-'denotes_#'(B,C,D,E,A),denotes_1(E).
trace(A,B):-'denotes_#'(C,D,E,F,B),denotes_0(F),denotes_0(E),denotes_0(D),denotes_0(C),'denotes_#'(G,H,I,J,A),denotes_1(I).
trace(A):-'denotes_#'(B,C,D,E,A),denotes_0(E),denotes_1(D),denotes_0(C),denotes_0(B).
adv(A):-'denotes_#'(B,C,D,E,A),denotes_1(E),denotes_0(D),denotes_0(C),denotes_0(B).
empty(A):-'denotes_#'(B,C,D,E,A),denotes_0(E),denotes_0(D),denotes_0(C),denotes_0(B).
np_all(A):-'denotes_#'(B,C,D,E,A),denotes_0(E),denotes_1(D),denotes_1(C),denotes_1(B).
s_all(A):-'denotes_#'(B,C,D,E,A),denotes_1(E),denotes_1(D),denotes_0(C),denotes_1(B).
np_no_trace(A):-'denotes_#'(B,C,D,E,A),denotes_0(E),denotes_0(D),denotes_1(C),denotes_1(B).
myplus(A,B,C):-or(D,E,F),or(G,H,I),or(J,K,L),or(M,N,O),'denotes_#'(F,I,L,O,C),'denotes_#'(E,H,K,N,B),'denotes_#'(D,G,J,M,A).
minus(A,B,C):-anot(D,E,F),anot(G,H,I),anot(J,K,L),anot(M,N,O),'denotes_#'(F,I,L,O,C),'denotes_#'(E,H,K,N,B),'denotes_#'(D,G,J,M,A).
or(A,B,C):-denotes_1(C),denotes_1(A).
or(A,B,C):-denotes_1(C),denotes_1(B),denotes_0(A).
or(A,B,C):-denotes_0(C),denotes_0(B),denotes_0(A).
anot(A,B,A):-denotes_0(B).
anot(A,B,C):-denotes_0(C),denotes_1(B).
role(A,B,C):-'denotes_#'(D,E,F,C),denotes_0(F),denotes_0(E),denotes_1(D),denotes_subj(A).
role(A,B,C):-'denotes_#'(D,E,F,C),denotes_0(D),denotes_compl(A).
role(A,B,C):-'denotes_#'(D,E,F,C),denotes_0(E),denotes_main(B),denotes_undef(A).
role(A,B,C):-'denotes_#'(D,E,F,C),denotes_0(D),denotes_aux(B),denotes_undef(A).
role(A,B,C):-denotes_decl(B),denotes_undef(A).
role(A,B,C):-denotes_nil(A).
subj_case(A):-'denotes_#'(B,C,D,A),denotes_0(D),denotes_0(C),denotes_1(B).
verb_case(A):-'denotes_#'(B,C,D,A),denotes_0(D),denotes_1(C),denotes_0(B).
prep_case(A):-'denotes_#'(B,C,D,A),denotes_1(D),denotes_0(C),denotes_0(B).
compl_case(A):-'denotes_#'(B,C,D,A),denotes_0(B).
say(A,B):-sentence(B,A,C,D,E),'denotes_[]'(E),'denotes_[]'(D),'denotes_[]'(C).
sentence(A,B,C,D,E):-declarative(A,B,F,D,G),terminator(H,F,C,G,E),'denotes_.'(H).
sentence(A,B,C,D,E):-wh_question(A,B,F,D,G),terminator(H,F,C,G,E),'denotes_?'(H).
sentence(A,B,C,D,E):-topic(B,F,D,G),wh_question(A,F,H,G,I),terminator(J,H,C,I,E),'denotes_?'(J).
sentence(A,B,C,D,E):-yn_question(A,B,F,D,G),terminator(H,F,C,G,E),'denotes_?'(H).
sentence(A,B,C,D,E):-imperative(A,B,F,D,G),terminator(H,F,C,G,E),'denotes_!'(H).
pp(A,B,C,D,E,E,F,G):-virtual(H,F,G),denotes_pp(A,B,C,D,H).
pp(A,B,C,D,E,F,G,H):-prep(I,E,J,G,K),prep_case(L),np(M,N,L,O,B,C,D,J,F,K,H),denotes_pp(I,M,A).
topic(A,B,C,D):-pp(E,F,G,H,A,I,C,J),opt_comma(I,B,J,K),denotes_compl(F),denotes_x(L,M,N,K,D),denotes_pp(E,O,G,H,N),denotes_compl(O),denotes_nonterminal(M),denotes_gap(L).
opt_comma(A,B,C,D):- `(E,A,B,C,D),'denotes_,'(E).
opt_comma(A,A,B,B):-true.
declarative(A,B,C,D,E):-s(F,G,B,C,D,E),denotes_decl(F,A).
wh_question(A,B,C,D,E):-variable_q(F,G,H,I,B,J,D,K),question(H,I,L,J,C,K,E),denotes_whq(F,L,A).
np(A,B,C,D,E,F,G,H,H,I,J):-virtual(K,I,J),denotes_np(A,B,C,D,E,F,G,K).
np(A,B,C,D,E,F,G,H,I,J,K):-is_pp(F),pers_pron(L,B,M,H,I,J,K),empty(G),role(M,N,C),denotes_decl(N),denotes_def(D),denotes_np(B,L,O,A),'denotes_[]'(O).
np(A,B,C,D,E,F,G,H,I,J,K):-is_pp(F),np_head(L,B,M,N,O,H,P,J,Q),np_all(R),np_compls(S,B,E,N,R,G,P,I,Q,K),'denotes_+'(D,S,M),denotes_np(B,L,O,A).
np(A,B,C,D,E,F,G,H,I,J,K):-is_pp(F),determiner(L,M,N,H,O,J,P),`(Q,O,R,P,S),s_all(T),prep_case(U),np(V,W,U,X,E,T,G,R,I,S,K),denotes_def(X),'denotes_+'(Y,Z,W),denotes_plu(Z),denotes_3(Y),denotes_of(Q),denotes_indef(N),denotes_indef(D),'denotes_+'(A1,M,B),denotes_3(A1),denotes_part(L,V,A).
variable_q(A,B,C,D,E,F,G,H):-whq(A,B,I,C,E,F,G,J),trace(K,L),denotes_x(M,N,O,J,H),denotes_np(I,B,D,P,Q,K,L,O),denotes_nonterminal(N),denotes_gap(M).
variable_q(A,B,C,D,E,F,G,H):-prep(I,E,J,G,K),whq(A,B,L,M,J,F,K,N),trace(O,P),compl_case(D),denotes_x(Q,R,S,N,H),denotes_pp(T,U,O,P,S),denotes_compl(U),denotes_pp(I,L,T),denotes_nonterminal(R),denotes_gap(Q),denotes_compl(C).
variable_q(A,B,C,D,E,F,G,H):-context_pron(I,J,E,F,G,K),trace(L,M),verb_case(D),denotes_x(N,O,P,K,H),denotes_adv_phrase(Q,L,M,P),denotes_pp(I,R,Q),denotes_np(B,S,T,R),'denotes_[]'(T),denotes_np_head(U,V,J,S),'denotes_[]'(V),denotes_int_det(A,U),denotes_nonterminal(O),denotes_gap(N),denotes_compl(C).
variable_q(A,B,C,D,E,F,G,H):- `(I,E,J,G,K),adj(L,M,J,F,K,N),empty(O),verb_case(D),denotes_quant(L),denotes_how(I),denotes_x(P,Q,R,N,H),denotes_predicate(S,T,O,R),denotes_value(M,U,T),denotes_wh(A,U),denotes_adj(S),denotes_nonterminal(Q),denotes_gap(P),denotes_compl(C).
adv_phrase(A,B,C,D,D,E,F):-virtual(G,E,F),denotes_adv_phrase(A,B,C,G).
adv_phrase(A,B,C,D,E,F,G):-loc_pred(H,D,I,F,J),pp(K,L,B,C,I,E,J,G),denotes_compl(L),denotes_pp(M,N,K),denotes_prep(O,M),denotes_of(O),denotes_pp(H,N,A).
predicate(A,B,C,D,D,E,F):-virtual(G,E,F),denotes_predicate(A,B,C,G).
predicate(A,B,C,D,E,F,G):-adj_phrase(B,C,D,E,F,G).
predicate(A,B,C,D,E,F,G):-s_all(H),pp(B,I,H,C,D,E,F,G),denotes_compl(I),denotes_neg(A).
predicate(A,B,C,D,E,F,G):-s_all(H),adv_phrase(B,H,C,D,E,F,G).
whq(A,B,C,D,E,F,G,H):-int_det(A,B,E,I,G,J),s_all(K),np(C,B,L,M,N,K,O,I,F,J,H),denotes_subj(N),denotes_undef(D).
whq(A,B,C,D,E,F,G,H):-int_pron(D,E,F,G,H),denotes_np(I,J,K,C),'denotes_[]'(K),denotes_wh(A,J),'denotes_+'(L,M,I),denotes_3(L),'denotes_+'(N,M,B),denotes_3(N).
int_det(A,B,C,D,E,F):-whose(A,G,C,D,E,F),'denotes_+'(H,G,B),denotes_3(H).
int_det(A,B,C,D,E,F):-int_art(A,G,C,D,E,F),'denotes_+'(H,G,B),denotes_3(H).
gen_marker(A,A,B,C):-virtual(D,B,C),denotes_gen_marker(D).
gen_marker(A,B,C,D):- `(E,A,F,C,G),an_s(F,B,G,D),'denotes_`'(E).
whose(A,B,C,D,E,F):- `(G,C,D,E,H),denotes_whose(G),denotes_x(I,J,K,L,F),denotes_x(M,N,O,H,L),denotes_gen_marker(O),denotes_nonterminal(N),denotes_nogap(M),denotes_np_head0(P,B,Q,K),denotes_proper(Q),denotes_wh(A,P),denotes_nonterminal(J),denotes_nogap(I).
question(A,B,C,D,E,F,G):-subj_question(A),role(H,I,B),s(C,J,D,E,F,G),denotes_subj(H).
question(A,B,C,D,E,F,G):-fronted_verb(A,B,D,H,F,I),s(C,J,H,E,I,G).
det(A,B,C,D,D,E,F):-virtual(G,E,F),denotes_det(A,B,C,G).
det(A,B,C,D,E,F,G):-terminal(H,D,E,F,G),det(H,B,I,C),denotes_det(I,A).
det(A,B,C,D,D,E,E):-denotes_generic(C),denotes_generic(A).
int_art(A,B,C,D,E,F):-int_art(A,B,G,C,D,E,H),denotes_x(I,J,K,H,F),denotes_det(G,B,L,K),denotes_def(L),denotes_nonterminal(J),denotes_nogap(I).
subj_question(A):-denotes_subj(A).
subj_question(A):-denotes_undef(A).
yn_question(A,B,C,D,E):-fronted_verb(F,G,B,H,D,I),s(J,K,H,C,I,E),denotes_nil(F),denotes_q(J,A).
verb_form(A,B,C,D,E,E,F,G):-virtual(H,F,G),denotes_verb_form(A,B,C,D,H).
verb_form(A,B,C,D,E,F,G,H):-terminal(I,E,F,G,H),verb_form(I,A,B,C).
neg(A,B,C,C,D,E):-virtual(F,D,E),denotes_neg(A,B,F).
neg(A,B,C,D,E,F):- `(G,C,D,E,F),denotes_not(G),denotes_neg(B),'denotes_+'(H,I,A),denotes_aux(H).
neg(A,B,C,C,D,D):-denotes_pos(B).
fronted_verb(A,B,C,D,E,F):-verb_form(G,H,I,J,C,K,E,L),verb_type(G,M),role(A,N,B),neg(O,P,K,D,L,Q),'denotes_+'(R,S,M),denotes_aux(R),denotes_x(T,U,V,W,F),denotes_x(X,Y,Z,Q,W),denotes_neg(A1,P,Z),denotes_nonterminal(Y),denotes_nogap(X),denotes_verb_form(G,H,I,N,V),denotes_nonterminal(U),denotes_gap(T).
imperative(A,B,C,D,E):-imperative_verb(B,F,D,G),s(H,I,F,C,G,E),denotes_imp(H,A).
imperative_verb(A,B,C,D):-verb_form(E,F,G,H,A,B,C,I),denotes_inf(F),denotes_x(J,K,L,M,D),denotes_x(N,O,P,I,M),denotes_verb_form(E,Q,R,S,P),denotes_main(S),'denotes_+'(T,U,R),denotes_sin(U),denotes_2(T),'denotes_+'(V,W,Q),denotes_fin(W),denotes_imp(V),denotes_nonterminal(O),denotes_nogap(N),denotes_you(L),denotes_terminal(K),denotes_nogap(J).
s(A,B,C,D,E,F):-subj(G,H,I,C,J,E,K),verb(L,H,I,M,J,N,K,O),empty(P),s_all(Q),verb_args(I,M,R,P,S,N,T,O,U),minus(Q,S,V),myplus(Q,S,W),verb_mods(X,V,W,B,T,D,U,F),denotes_s(G,L,R,X,A).
subj(A,B,C,D,E,F,G):- `(H,D,E,F,G),denotes_there(H),'denotes_+'(I,J,C),denotes_be(J),denotes_there(A).
subj(A,B,C,D,E,F,G):-s_all(H),subj_case(I),np(A,B,I,J,K,H,L,D,E,F,G),denotes_subj(K).
np_head(A,B,C,D,E,F,G,H,I):-np_head0(J,K,L,F,M,H,N),possessive(J,K,L,O,O,A,B,C,D,E,M,G,N,I).
np_head0(A,B,C,D,D,E,F):-virtual(G,E,F),denotes_np_head0(A,B,C,G).
np_head0(A,B,C,D,E,F,G):-name(H,D,E,F,G),'denotes_+'(I,J,C),denotes_proper(J),denotes_def(I),'denotes_+'(K,L,B),denotes_sin(L),denotes_3(K),denotes_name(H,A).
np_head0(A,B,C,D,E,F,G):-determiner(H,I,J,D,K,F,L),adjs(M,K,N,L,O),noun(P,I,N,E,O,G),'denotes_+'(J,Q,C),denotes_common(Q),'denotes_+'(R,I,B),denotes_3(R),denotes_np_head(H,M,P,A).
np_head0(A,B,C,D,E,F,G):-poss_pron(A,B,D,E,F,H),denotes_x(I,J,K,H,G),denotes_gen_marker(K),denotes_nonterminal(J),denotes_nogap(I),'denotes_+'(L,M,C),denotes_proper(M),denotes_def(L).
np_head0(A,B,C,D,E,F,G):-quantifier_pron(H,I,D,E,F,G),'denotes_+'(J,K,C),denotes_common(K),denotes_indef(J),'denotes_+'(L,M,B),denotes_sin(M),denotes_3(L),denotes_np_head(H,N,I,A),'denotes_[]'(N).
np_compls(A,B,C,D,E,F,G,G,H,H):-empty(F),'denotes_[]'(D),denotes_proper(A).
np_compls(A,B,C,D,E,F,G,H,I,J):-np_all(K),np_mods(B,C,L,D,E,M,K,N,G,O,I,P),relative(B,L,M,N,F,O,H,P,J),denotes_common(A).
possessive(A,B,C,D,E,F,G,H,I,J,K,L,M,N):-gen_case(K,O,M,P),np_head0(Q,R,S,O,T,P,U),possessive(Q,R,S,V,W,F,G,H,I,J,T,L,U,N),'denotes_.'(X,V,W),denotes_pp(Y,Z,X),denotes_np(B,A,E,Z),denotes_poss(Y),'denotes_[]'(D).
possessive(A,B,C,D,E,A,B,C,D,E,F,F,G,G):-true.
gen_case(A,B,C,D):-gen_marker(A,B,C,E),denotes_x(F,G,H,E,D),denotes_the(H),denotes_terminal(G),denotes_nogap(F).
an_s(A,B,C,D):- `(E,A,B,C,D),denotes_s(E).
an_s(A,A,B,B):-true.
determiner(A,B,C,D,E,F,G):-det(A,B,C,D,E,F,G).
determiner(A,B,C,D,E,F,G):-quant_phrase(A,B,C,D,E,F,G).
quant_phrase(A,B,C,D,E,F,G):-quant(H,C,D,I,F,J),number(K,B,I,E,J,G),denotes_quant(H,K,A).
quant(A,B,C,D,E,F):-neg_adv(G,A,C,H,E,I),comp_adv(G,H,J,I,K),`(L,J,D,K,F),denotes_than(L),denotes_indef(B).
quant(A,B,C,D,E,F):- `(G,C,H,E,I),sup_adv(J,H,D,I,F),sup_op(J,A),denotes_at(G),denotes_indef(B).
quant(A,B,C,D,E,F):- `(G,C,D,E,F),denotes_the(G),denotes_def(B),denotes_the(A).
quant(A,B,C,C,D,D):-denotes_indef(B),denotes_same(A).
neg_adv(A,B,C,D,E,F):- `(G,C,D,E,F),denotes_not(G),denotes_not(H,B),'denotes_+'(A,H).
neg_adv(A,A,B,B,C,C):-true.
sup_op(A,B):-denotes_not(C,B),'denotes_+'(D,C),denotes_less(D),denotes_least(A).
sup_op(A,B):-denotes_not(C,B),'denotes_+'(D,C),denotes_more(D),denotes_most(A).
np_mods(A,B,C,D,E,F,G,H,I,J,K,L):-np_mod(A,B,M,E,N,I,O,K,P),trace(Q),myplus(Q,N,R),minus(E,R,S),myplus(N,E,T),np_mods(A,B,C,U,S,F,T,H,O,J,P,L),'denotes_.'(M,U,D).
np_mods(A,B,C,C,D,D,E,E,F,F,G,G):-true.
np_mod(A,B,C,D,E,F,G,H,I):-pp(C,B,D,E,F,G,H,I).
np_mod(A,B,C,D,E,F,G,H,I):-reduced_relative(A,C,D,E,F,G,H,I).
verb_mods(A,B,C,D,E,F,G,H):-verb_mod(I,B,J,E,K,G,L),trace(M),myplus(M,J,N),minus(B,N,O),myplus(J,B,P),verb_mods(Q,O,P,D,K,F,L,H),'denotes_.'(I,Q,A).
verb_mods(A,B,C,C,D,D,E,E):-'denotes_[]'(A).
verb_mod(A,B,C,D,E,F,G):-adv_phrase(A,B,C,D,E,F,G).
verb_mod(A,B,C,D,E,F,G):-is_adv(B),adverb(A,D,E,F,G),empty(C).
verb_mod(A,B,C,D,E,F,G):-pp(A,H,B,C,D,E,F,G),denotes_compl(H).
adjs(A,B,C,D,E):-pre_adj(F,B,G,D,H),adjs(I,G,C,H,E),'denotes_.'(F,I,A).
adjs(A,B,B,C,C):-'denotes_[]'(A).
pre_adj(A,B,C,D,E):-adj(F,A,B,C,D,E).
pre_adj(A,B,C,D,E):-sup_phrase(A,B,C,D,E).
sup_phrase(A,B,C,D,E):-sup_adj(F,B,C,D,E),denotes_sup(G,F,A),denotes_most(G).
sup_phrase(A,B,C,D,E):-sup_adv(F,B,G,D,H),adj(I,J,G,C,H,E),denotes_quant(I),denotes_sup(F,J,A).
comp_phrase(A,B,C,D,E,F):-comp(G,H,C,I,E,J),np_no_trace(K),prep_case(L),np(M,N,L,O,P,K,B,I,D,J,F),denotes_compl(P),denotes_comp(G,H,M,A).
comp(A,B,C,D,E,F):-comp_adv(A,C,G,E,H),adj(I,B,G,J,H,K),`(L,J,D,K,F),denotes_than(L),denotes_quant(I).
comp(A,B,C,D,E,F):-rel_adj(B,C,G,E,H),`(I,G,D,H,F),denotes_than(I),denotes_more(A).
comp(A,B,C,D,E,F):- `(G,C,H,E,I),adj(J,B,H,K,I,L),`(M,K,D,L,F),denotes_as(M),denotes_quant(J),denotes_as(G),denotes_same(A).
relative(A,B,C,D,E,F,G,H,I):-is_pred(C),rel_conj(A,J,K,E,F,G,H,I),'denotes_.'(K,L,B),'denotes_[]'(L).
relative(A,B,C,D,D,E,E,F,F):-'denotes_[]'(B).
rel_conj(A,B,C,D,E,F,G,H):-rel(A,I,J,E,K,G,L),rel_rest(A,B,I,C,J,D,K,F,L,H).
rel_rest(A,B,C,D,E,F,G,H,I,J):-conj(B,K,C,L,D,G,M,I,N),rel_conj(A,K,L,F,M,H,N,J).
rel_rest(A,B,C,C,D,D,E,E,F,F):-true.
rel(A,B,C,D,E,F,G):-open(D,H,F,I),variable(A,J,H,K,I,L),s(M,N,K,O,L,P),trace(Q),minus(N,Q,C),close(O,E,P,G),denotes_rel(J,M,B).
variable(A,B,C,D,E,F):- `(G,C,D,E,H),trace(I,J),denotes_that(G),denotes_x(K,L,M,H,F),denotes_np(N,A,O,P,Q,I,J,M),denotes_np(A,R,S,N),'denotes_[]'(S),denotes_wh(B,R),denotes_nonterminal(L),denotes_gap(K).
variable(A,B,C,D,E,F):-wh(B,A,G,H,I,C,D,E,J),trace(K,L),denotes_x(M,N,O,J,F),denotes_np(G,H,I,P,Q,K,L,O),denotes_nonterminal(N),denotes_gap(M).
variable(A,B,C,D,E,F):-prep(G,C,H,E,I),wh(B,A,J,K,L,H,D,I,M),trace(N,O),compl_case(L),denotes_x(P,Q,R,M,F),denotes_pp(S,T,N,O,R),denotes_compl(T),denotes_pp(G,J,S),denotes_nonterminal(Q),denotes_gap(P).
wh(A,B,C,B,D,E,F,G,H):-rel_pron(I,E,F,G,H),role(I,J,D),denotes_decl(J),denotes_np(B,K,L,C),'denotes_[]'(L),denotes_wh(A,K).
wh(A,B,C,D,E,F,G,H,I):-np_head0(J,D,K,F,L,H,M),prep(N,L,O,M,P),wh(A,B,Q,R,S,O,G,P,I),'denotes_+'(T,U,K),denotes_common(U),denotes_np(D,J,V,C),'denotes_.'(W,X,V),'denotes_[]'(X),denotes_pp(N,Q,W).
wh(A,B,C,D,E,F,G,H,I):-whose(A,B,F,J,H,K),s_all(L),np(C,D,E,M,N,L,O,J,G,K,I),denotes_subj(N),denotes_def(M).
reduced_relative(A,B,C,D,E,F,G,H):-is_pred(C),reduced_rel_conj(A,I,B,D,E,F,G,H).
reduced_rel_conj(A,B,C,D,E,F,G,H):-reduced_rel(A,I,J,E,K,G,L),reduced_rel_rest(A,B,I,C,J,D,K,F,L,H).
reduced_rel_rest(A,B,C,D,E,F,G,H,I,J):-conj(B,K,C,L,D,G,M,I,N),reduced_rel_conj(A,K,L,F,M,H,N,J).
reduced_rel_rest(A,B,C,C,D,D,E,E,F,F):-true.
reduced_rel(A,B,C,D,E,F,G):-open(D,H,F,I),reduced_wh(A,J,H,K,I,L),s(M,N,K,O,L,P),trace(Q),minus(N,Q,C),close(O,E,P,G),denotes_reduced_rel(J,M,B).
reduced_wh(A,B,C,D,E,F):-neg(G,H,C,I,E,J),predicate(H,K,L,I,D,J,M),trace(N,O),subj_case(P),denotes_x(Q,R,S,T,F),denotes_x(U,V,W,X,T),denotes_x(Y,Z,A1,B1,X),denotes_x(C1,D1,E1,M,B1),denotes_predicate(H,K,L,E1),denotes_nonterminal(D1),denotes_nogap(C1),denotes_neg(F1,H,A1),denotes_nonterminal(Z),denotes_nogap(Y),denotes_verb_form(G1,H1,A,I1,W),denotes_main(I1),'denotes_+'(J1,K1,H1),denotes_fin(K1),denotes_pres(J1),denotes_be(G1),denotes_nonterminal(V),denotes_nogap(U),denotes_np(L1,A,P,M1,N1,N,O,S),denotes_np(A,O1,P1,L1),'denotes_[]'(P1),denotes_wh(B,O1),denotes_nonterminal(R),denotes_nogap(Q).
reduced_wh(A,B,C,D,E,F):-participle(G,H,I,C,D,E,J),trace(K,L),subj_case(M),denotes_x(N,O,P,Q,F),denotes_x(R,S,T,J,Q),denotes_verb(G,U,H,I,T),denotes_nonterminal(S),denotes_nogap(R),denotes_np(V,A,M,W,X,K,L,P),denotes_np(A,Y,Z,V),'denotes_[]'(Z),denotes_wh(B,Y),denotes_nonterminal(O),denotes_nogap(N).
reduced_wh(A,B,C,D,E,F):-s_all(G),subj_case(H),verb_case(I),np(J,K,L,M,N,G,O,C,D,E,P),trace(Q,R),trace(S,T),denotes_subj(N),denotes_x(U,V,W,X,F),denotes_x(Y,Z,A1,P,X),denotes_np(B1,A,I,C1,D1,S,T,A1),denotes_np(A,E1,F1,B1),'denotes_[]'(F1),denotes_wh(B,E1),denotes_nonterminal(Z),denotes_gap(Y),denotes_np(J,K,H,M,G1,Q,R,W),denotes_nonterminal(V),denotes_nogap(U).
verb(A,B,C,D,E,E,F,G):-virtual(H,F,G),denotes_verb(A,B,C,D,H).
verb(A,B,C,D,E,F,G,H):-verb_form(I,J,B,K,E,L,G,M),verb_type(I,N),neg(N,O,L,P,M,Q),rest_verb(K,I,R,D,S,P,F,Q,H),verb_type(R,C),'denotes_+'(T,U,J),denotes_fin(U),denotes_verb(R,D,V,S,O,A),'denotes_+'(T,W,V),denotes_fin(W).
rest_verb(A,B,C,D,E,F,G,H,I):-verb_form(J,K,L,M,F,N,H,O),have(J,C,D,P,N,G,O,I),'denotes_+'(Q,R,K),denotes_part(R),denotes_past(Q),'denotes_.'(S,P,E),denotes_perf(S),denotes_have(B),denotes_aux(A).
rest_verb(A,B,C,D,E,F,G,H,I):-verb_form(J,K,L,M,F,N,H,O),be(K,J,C,D,E,N,G,O,I),denotes_be(B),denotes_aux(A).
rest_verb(A,B,C,D,E,F,G,H,I):-verb_form(C,J,K,L,F,G,H,I),denotes_inf(J),'denotes_[]'(E),denotes_active(D),denotes_do(B),denotes_aux(A).
rest_verb(A,B,B,C,D,E,E,F,F):-'denotes_[]'(D),denotes_active(C),denotes_main(A).
have(A,B,C,D,E,F,G,H):-verb_form(I,J,K,L,E,M,G,N),be(J,I,B,C,D,M,F,N,H),denotes_be(A).
have(A,A,B,C,D,D,E,E):-'denotes_[]'(C),denotes_active(B).
be(A,B,B,C,D,E,E,F,F):-'denotes_[]'(D),denotes_passive(C),'denotes_+'(G,H,A),denotes_part(H),denotes_past(G).
be(A,B,C,D,E,F,G,H,I):-passive(B,C,D,F,G,H,I),'denotes_.'(J,K,E),'denotes_[]'(K),denotes_prog(J),'denotes_+'(L,M,A),denotes_part(M),denotes_pres(L).
passive(A,B,C,D,E,F,G):-verb_form(B,H,I,J,D,E,F,G),verb_type(B,K),passive(K),'denotes_+'(L,M,H),denotes_part(M),denotes_past(L),denotes_passive(C),denotes_be(A).
passive(A,A,B,C,C,D,D):-denotes_active(B).
participle(A,B,C,D,E,F,G):-neg(H,I,D,J,F,K),verb_form(L,M,N,O,J,E,K,G),participle(M,C,P),verb_type(L,B),denotes_verb(L,C,Q,P,I,A),denotes_inf(Q).
passive(A):-'denotes_+'(B,C,A),denotes_trans(C).
passive(A):-'denotes_+'(B,C,A),denotes_ditrans(C).
participle(A,B,C):-'denotes_.'(D,E,C),'denotes_[]'(E),denotes_prog(D),denotes_active(B),'denotes_+'(F,G,A),denotes_part(G),denotes_pres(F).
participle(A,B,C):-'denotes_[]'(C),denotes_passive(B),'denotes_+'(D,E,A),denotes_part(E),denotes_past(D).
close(A,A,B,C):-virtual(D,B,C),denotes_close(D).
open(A,A,B,C):-denotes_x(D,E,F,B,C),denotes_close(F),denotes_nonterminal(E),denotes_gap(D).
verb_args(A,B,C,D,E,F,G,H,I):-advs(C,J,K,F,L,H,M),verb_args(N,B,J,D,E,L,G,M,I),'denotes_+'(O,N,A).
verb_args(A,B,C,D,E,F,G,H,I):-verb_arg(J,K,E,F,G,H,I),denotes_np(J),'denotes_.'(L,M,C),'denotes_[]'(M),denotes_arg(N,K,L),denotes_dir(N),denotes_active(B),denotes_trans(A).
verb_args(A,B,C,D,E,F,G,H,I):-verb_arg(J,K,L,F,M,H,N),object(O,P,L,E,M,G,N,I),denotes_np(J),'denotes_.'(Q,P,C),denotes_arg(O,K,Q),denotes_ditrans(A).
verb_args(A,B,C,D,D,E,F,G,H):-terminal(I,E,F,G,H),denotes_there(I),'denotes_.'(J,K,C),'denotes_[]'(K),denotes_void(J),denotes_be(A).
verb_args(A,B,C,D,E,F,G,H,I):-pred_conj(J,K,E,F,G,H,I),'denotes_.'(L,M,C),'denotes_[]'(M),denotes_arg(N,K,L),denotes_predicate(N),denotes_be(A).
verb_args(A,B,C,D,E,F,G,H,I):-verb_arg(J,K,E,F,G,H,I),denotes_np(J),'denotes_.'(L,M,C),'denotes_[]'(M),denotes_arg(N,K,L),denotes_dir(N),denotes_be(A).
verb_args(A,B,C,D,E,F,G,H,I):-verb_arg(J,K,E,F,G,H,I),denotes_np(J),'denotes_.'(L,M,C),'denotes_[]'(M),denotes_arg(N,K,L),denotes_dir(N),denotes_active(B),denotes_have(A).
verb_args(A,B,C,D,D,E,E,F,F):-no_args(A),'denotes_[]'(C).
object(A,B,C,D,E,F,G,H):-adv(I),minus(I,C,J),advs(B,K,J,E,L,G,M),obj(A,K,C,D,L,F,M,H).
obj(A,B,C,D,E,F,G,H):-verb_arg(I,J,D,E,F,G,H),denotes_np(I),'denotes_.'(K,L,B),'denotes_[]'(L),denotes_arg(M,J,K),denotes_dir(M),denotes_ind(A).
obj(A,B,C,C,D,D,E,E):-'denotes_[]'(B),denotes_dir(A).
pred_conj(A,B,C,D,E,F,G):-predicate(H,I,J,D,K,F,L),pred_rest(A,I,B,J,C,K,E,L,G).
pred_rest(A,B,C,D,E,F,G,H,I):-conj(A,J,B,K,C,F,L,H,M),pred_conj(J,K,E,L,G,M,I).
pred_rest(A,B,B,C,C,D,D,E,E):-true.
verb_arg(A,B,C,D,E,F,G):-s_all(H),verb_case(I),np(B,J,I,K,L,H,C,D,E,F,G),denotes_compl(L),denotes_np(A).
advs(A,B,C,D,E,F,G):-is_adv(C),adverb(H,D,I,F,J),advs(K,B,C,I,E,J,G),'denotes_.'(H,K,A).
advs(A,A,B,C,C,D,D):-true.
adj_phrase(A,B,C,D,E,F):-adj(G,A,C,D,E,F),empty(B).
adj_phrase(A,B,C,D,E,F):-comp_phrase(A,B,C,D,E,F).
no_args(A):-denotes_trans(A).
no_args(A):-denotes_ditrans(A).
no_args(A):-denotes_intrans(A).
conj(A,B,C,D,E,F,G,H,I):-conj(J,K,L,F,G,H,I),denotes_conj(J,C,D,E),denotes_conj(J,L,B),denotes_conj(J,K,A).
noun(A,B,C,D,E,F):-terminal(G,C,D,E,F),noun_form(G,A,B).
adj(A,B,C,D,E,F):-terminal(G,C,D,E,F),adj(G,A),denotes_adj(G,B).
prep(A,B,C,D,E):-terminal(F,B,C,D,E),prep(F),denotes_prep(F,A).
rel_adj(A,B,C,D,E):-terminal(F,B,C,D,E),rel_adj(F,G),denotes_adj(G,A).
sup_adj(A,B,C,D,E):-terminal(F,B,C,D,E),sup_adj(F,G),denotes_adj(G,A).
comp_adv(A,B,C,D,E):- `(F,B,C,D,E),denotes_less(F),denotes_less(A).
comp_adv(A,B,C,D,E):- `(F,B,C,D,E),denotes_more(F),denotes_more(A).
sup_adv(A,B,C,D,E):- `(F,B,C,D,E),denotes_least(F),denotes_least(A).
sup_adv(A,B,C,D,E):- `(F,B,C,D,E),denotes_most(F),denotes_most(A).
rel_pron(A,B,C,D,E):-terminal(F,B,C,D,E),rel_pron(F,A).
name(A,B,C,D,E):-opt_the(B,F,D,G),terminal(A,F,C,G,E),name(A).
int_art(A,B,C,D,E,F,G):- `(H,D,I,F,J),`(K,I,E,J,G),denotes_many(K),denotes_how(H),denotes_quant(L,M,C),denotes_wh(A,M),denotes_same(L),denotes_plu(B).
int_art(A,B,C,D,E,F,G):-terminal(H,D,E,F,G),int_art(H,A,B,C).
int_pron(A,B,C,D,E):-terminal(F,B,C,D,E),int_pron(F,A).
adverb(A,B,C,D,E):-terminal(F,B,C,D,E),adverb(F),denotes_adv(F,A).
poss_pron(A,B,C,D,E,F):-terminal(G,C,D,E,F),poss_pron(G,H,I,J),'denotes_+'(I,J,B),denotes_pronoun(H,A).
pers_pron(A,B,C,D,E,F,G):-terminal(H,D,E,F,G),pers_pron(H,I,J,K,C),'denotes_+'(J,K,B),denotes_pronoun(I,A).
quantifier_pron(A,B,C,D,E,F):-terminal(G,C,D,E,F),quantifier_pron(G,A,B).
context_pron(A,B,C,D,E,F):- `(G,C,D,E,F),denotes_where(G),denotes_place(B),denotes_prep(H,A),denotes_in(H).
context_pron(A,B,C,D,E,F):- `(G,C,D,E,F),denotes_when(G),denotes_time(B),denotes_prep(H,A),denotes_at(H).
number(A,B,C,D,E,F):-terminal(G,C,D,E,F),number(G,H,B),denotes_nb(H,A).
terminator(A,B,C,D,E):-terminal(F,B,C,D,E),terminator(F,A).
opt_the(A,A,B,B):-true.
opt_the(A,B,C,D):- `(E,A,B,C,D),denotes_the(E).
conj(A,B,C,D,E,F,G):-terminal(H,D,E,F,G),'denotes_,'(H),denotes_list(C),denotes_list(B).
conj(A,B,C,D,E,F,G):-terminal(A,D,E,F,G),conj(A),denotes_end(C),denotes_list(B).
loc_pred(A,B,C,D,E):-terminal(F,B,C,D,E),loc_pred(F,A).
`(A,B,C,D,E):-terminal(A,B,C,D,E),`(A).
word(A):- `(A).
word(A):-conj(A).
word(A):-adverb(A).
word(A):-sup_adj(A,B).
word(A):-rel_adj(A,B).
word(A):-adj(A,B).
word(A):-name(A).
word(A):-terminator(A,B).
word(A):-pers_pron(A,B,C,D,E).
word(A):-poss_pron(A,B,C,D).
word(A):-rel_pron(A,B).
word(A):-verb_form(A,B,C,D).
word(A):-noun_form(A,B,C).
word(A):-prep(A).
word(A):-quantifier_pron(A,B,C).
word(A):-number(A,B,C).
word(A):-det(A,B,C,D).
word(A):-int_art(A,B,C,D).
word(A):-int_pron(A,B).
word(A):-loc_pred(A,B).
`(A):-denotes_how(A).
`(A):-denotes_whose(A).
`(A):-denotes_there(A).
`(A):-denotes_of(A).
`(A):-'denotes_`'(A).
`(A):-'denotes_,'(A).
`(A):-denotes_s(A).
`(A):-denotes_than(A).
`(A):-denotes_at(A).
`(A):-denotes_the(A).
`(A):-denotes_not(A).
`(A):-denotes_as(A).
`(A):-denotes_that(A).
`(A):-denotes_less(A).
`(A):-denotes_more(A).
`(A):-denotes_least(A).
`(A):-denotes_most(A).
`(A):-denotes_many(A).
`(A):-denotes_where(A).
`(A):-denotes_when(A).
conj(A):-denotes_and(A).
conj(A):-denotes_or(A).
int_pron(A,B):-denotes_undef(B),denotes_what(A).
int_pron(A,B):-denotes_undef(B),denotes_which(A).
int_pron(A,B):-denotes_subj(B),denotes_who(A).
int_pron(A,B):-denotes_compl(B),denotes_whom(A).
int_art(A,B,C,D):-denotes_int_det(B,D),denotes_what(A).
int_art(A,B,C,D):-denotes_int_det(B,D),denotes_which(A).
det(A,B,C,D):-denotes_def(D),denotes_the(B,C),denotes_the(A).
det(A,B,C,D):-denotes_indef(D),denotes_a(C),denotes_sin(B),denotes_a(A).
det(A,B,C,D):-denotes_indef(D),denotes_a(C),denotes_sin(B),denotes_an(A).
det(A,B,C,D):-denotes_indef(D),denotes_every(C),denotes_sin(B),denotes_every(A).
det(A,B,C,D):-denotes_indef(D),denotes_some(C),denotes_some(A).
det(A,B,C,D):-denotes_indef(D),denotes_any(C),denotes_any(A).
det(A,B,C,D):-denotes_indef(D),denotes_all(C),denotes_plu(B),denotes_all(A).
det(A,B,C,D):-denotes_indef(D),denotes_each(C),denotes_sin(B),denotes_each(A).
det(A,B,C,D):-denotes_indef(D),denotes_no(C),denotes_no(A).
number(A,B,C):-tr_number(A,B),ag_number(B,C).
tr_number(A,B):-denotes_nb(B,A).
tr_number(A,B):-denotes_1(B),denotes_one(A).
tr_number(A,B):-denotes_2(B),denotes_two(A).
tr_number(A,B):-denotes_3(B),denotes_three(A).
tr_number(A,B):-denotes_4(B),denotes_four(A).
tr_number(A,B):-denotes_5(B),denotes_five(A).
tr_number(A,B):-denotes_6(B),denotes_six(A).
tr_number(A,B):-denotes_7(B),denotes_seven(A).
tr_number(A,B):-denotes_8(B),denotes_eight(A).
tr_number(A,B):-denotes_9(B),denotes_nine(A).
tr_number(A,B):-denotes_10(B),denotes_ten(A).
ag_number(A,B):-denotes_sin(B),denotes_1(A).
ag_number(A,B):-gt(A,C),denotes_1(C),denotes_plu(B).
quantifier_pron(A,B,C):-denotes_person(C),denotes_every(B),denotes_everybody(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_every(B),denotes_everyone(A).
quantifier_pron(A,B,C):-denotes_thing(C),denotes_every(B),denotes_everything(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_some(B),denotes_somebody(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_some(B),denotes_someone(A).
quantifier_pron(A,B,C):-denotes_thing(C),denotes_some(B),denotes_something(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_any(B),denotes_anybody(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_any(B),denotes_anyone(A).
quantifier_pron(A,B,C):-denotes_thing(C),denotes_any(B),denotes_anything(A).
quantifier_pron(A,B,C):-denotes_person(C),denotes_no(B),denotes_nobody(A).
quantifier_pron(A,B,C):-denotes_thing(C),denotes_no(B),denotes_nothing(A).
prep(A):-denotes_as(A).
prep(A):-denotes_at(A).
prep(A):-denotes_of(A).
prep(A):-denotes_to(A).
prep(A):-denotes_by(A).
prep(A):-denotes_with(A).
prep(A):-denotes_in(A).
prep(A):-denotes_on(A).
prep(A):-denotes_from(A).
prep(A):-denotes_into(A).
prep(A):-denotes_through(A).
noun_form(A,B,C):-noun_plu(A,B),denotes_plu(C).
noun_form(A,A,B):-noun_sin(A),denotes_sin(B).
noun_form(A,B,C):-denotes_proportion(B),denotes_proportion(A).
noun_form(A,B,C):-denotes_percentage(B),denotes_percentage(A).
root_form(A):-'denotes_+'(B,C,A),denotes_sin(C),denotes_1(B).
root_form(A):-'denotes_+'(B,C,A),denotes_2(B).
root_form(A):-'denotes_+'(B,C,A),denotes_plu(C),denotes_1(B).
root_form(A):-'denotes_+'(B,C,A),denotes_plu(C),denotes_3(B).
verb_root(A):-denotes_be(A).
verb_root(A):-denotes_have(A).
verb_root(A):-denotes_do(A).
verb_root(A):-denotes_border(A).
verb_root(A):-denotes_contain(A).
verb_root(A):-denotes_drain(A).
verb_root(A):-denotes_exceed(A).
verb_root(A):-denotes_flow(A).
verb_root(A):-denotes_rise(A).
regular_pres(A):-denotes_have(A).
regular_pres(A):-denotes_do(A).
regular_pres(A):-denotes_rise(A).
regular_pres(A):-denotes_border(A).
regular_pres(A):-denotes_contain(A).
regular_pres(A):-denotes_drain(A).
regular_pres(A):-denotes_exceed(A).
regular_pres(A):-denotes_flow(A).
regular_past(A,B):-denotes_have(B),denotes_had(A).
regular_past(A,B):-denotes_border(B),denotes_bordered(A).
regular_past(A,B):-denotes_contain(B),denotes_contained(A).
regular_past(A,B):-denotes_drain(B),denotes_drained(A).
regular_past(A,B):-denotes_exceed(B),denotes_exceeded(A).
regular_past(A,B):-denotes_flow(B),denotes_flowed(A).
rel_pron(A,B):-denotes_subj(B),denotes_who(A).
rel_pron(A,B):-denotes_compl(B),denotes_whom(A).
rel_pron(A,B):-denotes_undef(B),denotes_which(A).
poss_pron(A,B,C,D):-denotes_sin(D),denotes_1(C),denotes_my(A).
poss_pron(A,B,C,D):-denotes_2(C),denotes_your(A).
poss_pron(A,B,C,D):-denotes_sin(D),denotes_3(C),denotes_masc(B),denotes_his(A).
poss_pron(A,B,C,D):-denotes_sin(D),denotes_3(C),denotes_fem(B),denotes_her(A).
poss_pron(A,B,C,D):-denotes_sin(D),denotes_3(C),denotes_neut(B),denotes_its(A).
poss_pron(A,B,C,D):-denotes_plu(D),denotes_1(C),denotes_our(A).
poss_pron(A,B,C,D):-denotes_plu(D),denotes_3(C),denotes_their(A).
pers_pron(A,B,C,D,E):-denotes_subj(E),denotes_sin(D),denotes_1(C),denotes_i(A).
pers_pron(A,B,C,D,E):-denotes_2(C),denotes_you(A).
pers_pron(A,B,C,D,E):-denotes_subj(E),denotes_sin(D),denotes_3(C),denotes_masc(B),denotes_he(A).
pers_pron(A,B,C,D,E):-denotes_subj(E),denotes_sin(D),denotes_3(C),denotes_fem(B),denotes_she(A).
pers_pron(A,B,C,D,E):-denotes_sin(D),denotes_3(C),denotes_neut(B),denotes_it(A).
pers_pron(A,B,C,D,E):-denotes_subj(E),denotes_plu(D),denotes_1(C),denotes_we(A).
pers_pron(A,B,C,D,E):-denotes_subj(E),denotes_plu(D),denotes_3(C),denotes_them(A).
pers_pron(A,B,C,D,E):-denotes_compl(F,E),denotes_sin(D),denotes_1(C),denotes_me(A).
pers_pron(A,B,C,D,E):-denotes_compl(F,E),denotes_sin(D),denotes_3(C),denotes_masc(B),denotes_him(A).
pers_pron(A,B,C,D,E):-denotes_compl(F,E),denotes_sin(D),denotes_3(C),denotes_fem(B),denotes_her(A).
pers_pron(A,B,C,D,E):-denotes_compl(F,E),denotes_plu(D),denotes_1(C),denotes_us(A).
pers_pron(A,B,C,D,E):-denotes_compl(F,E),denotes_plu(D),denotes_3(C),denotes_them(A).
terminator(A,B):-'denotes_.'(A).
terminator(A,B):-'denotes_?'(B),'denotes_?'(A).
terminator(A,B):-'denotes_!'(B),'denotes_!'(A).
name(A):-true.
loc_pred(A,B):-denotes_prep(C,B),denotes_eastof(C),denotes_east(A).
loc_pred(A,B):-denotes_prep(C,B),denotes_westof(C),denotes_west(A).
loc_pred(A,B):-denotes_prep(C,B),denotes_northof(C),denotes_north(A).
loc_pred(A,B):-denotes_prep(C,B),denotes_southof(C),denotes_south(A).
adj(A,B):-denotes_restr(B),denotes_minimum(A).
adj(A,B):-denotes_restr(B),denotes_maximum(A).
adj(A,B):-denotes_restr(B),denotes_average(A).
adj(A,B):-denotes_restr(B),denotes_total(A).
adj(A,B):-denotes_restr(B),denotes_african(A).
adj(A,B):-denotes_restr(B),denotes_american(A).
adj(A,B):-denotes_restr(B),denotes_asian(A).
adj(A,B):-denotes_restr(B),denotes_european(A).
adj(A,B):-denotes_quant(B),denotes_great(A).
adj(A,B):-denotes_quant(B),denotes_big(A).
adj(A,B):-denotes_quant(B),denotes_small(A).
adj(A,B):-denotes_quant(B),denotes_large(A).
adj(A,B):-denotes_quant(B),denotes_old(A).
adj(A,B):-denotes_quant(B),denotes_new(A).
adj(A,B):-denotes_quant(B),denotes_populous(A).
rel_adj(A,B):-denotes_great(B),denotes_greater(A).
rel_adj(A,B):-denotes_small(B),denotes_less(A).
rel_adj(A,B):-denotes_big(B),denotes_bigger(A).
rel_adj(A,B):-denotes_small(B),denotes_smaller(A).
rel_adj(A,B):-denotes_large(B),denotes_larger(A).
rel_adj(A,B):-denotes_old(B),denotes_older(A).
rel_adj(A,B):-denotes_new(B),denotes_newer(A).
sup_adj(A,B):-denotes_big(B),denotes_biggest(A).
sup_adj(A,B):-denotes_small(B),denotes_smallest(A).
sup_adj(A,B):-denotes_large(B),denotes_largest(A).
sup_adj(A,B):-denotes_old(B),denotes_oldest(A).
sup_adj(A,B):-denotes_new(B),denotes_newest(A).
noun_sin(A):-denotes_average(A).
noun_sin(A):-denotes_total(A).
noun_sin(A):-denotes_sum(A).
noun_sin(A):-denotes_degree(A).
noun_sin(A):-denotes_sqmile(A).
noun_sin(A):-denotes_ksqmile(A).
noun_sin(A):-denotes_thousand(A).
noun_sin(A):-denotes_million(A).
noun_sin(A):-denotes_time(A).
noun_sin(A):-denotes_place(A).
noun_sin(A):-denotes_area(A).
noun_sin(A):-denotes_capital(A).
noun_sin(A):-denotes_city(A).
noun_sin(A):-denotes_continent(A).
noun_sin(A):-denotes_country(A).
noun_sin(A):-denotes_latitude(A).
noun_sin(A):-denotes_longitude(A).
noun_sin(A):-denotes_ocean(A).
noun_sin(A):-denotes_person(A).
noun_sin(A):-denotes_population(A).
noun_sin(A):-denotes_region(A).
noun_sin(A):-denotes_river(A).
noun_sin(A):-denotes_sea(A).
noun_sin(A):-denotes_seamass(A).
noun_sin(A):-denotes_number(A).
noun_plu(A,B):-denotes_average(B),denotes_averages(A).
noun_plu(A,B):-denotes_total(B),denotes_totals(A).
noun_plu(A,B):-denotes_sum(B),denotes_sums(A).
noun_plu(A,B):-denotes_degree(B),denotes_degrees(A).
noun_plu(A,B):-denotes_sqmile(B),denotes_sqmiles(A).
noun_plu(A,B):-denotes_ksqmile(B),denotes_ksqmiles(A).
noun_plu(A,B):-denotes_million(B),denotes_million(A).
noun_plu(A,B):-denotes_thousand(B),denotes_thousand(A).
noun_plu(A,B):-denotes_time(B),denotes_times(A).
noun_plu(A,B):-denotes_place(B),denotes_places(A).
noun_plu(A,B):-denotes_area(B),denotes_areas(A).
noun_plu(A,B):-denotes_capital(B),denotes_capitals(A).
noun_plu(A,B):-denotes_city(B),denotes_cities(A).
noun_plu(A,B):-denotes_continent(B),denotes_continents(A).
noun_plu(A,B):-denotes_country(B),denotes_countries(A).
noun_plu(A,B):-denotes_latitude(B),denotes_latitudes(A).
noun_plu(A,B):-denotes_longitude(B),denotes_longitudes(A).
noun_plu(A,B):-denotes_ocean(B),denotes_oceans(A).
noun_plu(A,B):-denotes_person(B),denotes_persons(A).
noun_plu(A,B):-denotes_person(B),denotes_people(A).
noun_plu(A,B):-denotes_population(B),denotes_populations(A).
noun_plu(A,B):-denotes_region(B),denotes_regions(A).
noun_plu(A,B):-denotes_river(B),denotes_rivers(A).
noun_plu(A,B):-denotes_sea(B),denotes_seas(A).
noun_plu(A,B):-denotes_seamass(B),denotes_seamasses(A).
noun_plu(A,B):-denotes_number(B),denotes_numbers(A).
verb_form(A,A,B,C):-verb_root(A),denotes_inf(B).
verb_form(A,A,B,C):-regular_pres(A),root_form(C),verb_root(A),'denotes_+'(D,E,B),denotes_fin(E),denotes_pres(D).
verb_form(A,B,C,D):-regular_past(A,B),'denotes_+'(E,F,C),denotes_past(E).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_1(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_be(B),denotes_am(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_2(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_be(B),denotes_are(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_be(B),denotes_is(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_plu(F),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_be(B),denotes_are(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_1(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_past(G),denotes_be(B),denotes_was(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_2(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_past(G),denotes_be(B),denotes_were(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_past(G),denotes_be(B),denotes_was(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_plu(F),'denotes_+'(G,H,C),denotes_fin(H),denotes_past(G),denotes_be(B),denotes_were(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_past(E),denotes_be(B),denotes_been(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_be(B),denotes_being(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_have(B),denotes_has(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_have(B),denotes_having(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_do(B),denotes_does(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_fin(F),denotes_past(E),denotes_do(B),denotes_did(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_do(B),denotes_doing(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_past(E),denotes_do(B),denotes_done(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_flow(B),denotes_flows(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_flow(B),denotes_flowing(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_rise(B),denotes_rises(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_fin(F),denotes_past(E),denotes_rise(B),denotes_rose(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_past(E),denotes_rise(B),denotes_risen(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_border(B),denotes_borders(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_border(B),denotes_bordering(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_contain(B),denotes_contains(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_contain(B),denotes_containing(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_drain(B),denotes_drains(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_drain(B),denotes_draining(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,D),denotes_sin(F),denotes_3(E),'denotes_+'(G,H,C),denotes_fin(H),denotes_pres(G),denotes_exceed(B),denotes_exceeds(A).
verb_form(A,B,C,D):-'denotes_+'(E,F,C),denotes_part(F),denotes_pres(E),denotes_exceed(B),denotes_exceeding(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_have(D),denotes_aux(C),denotes_have(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_be(D),denotes_aux(C),denotes_be(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_ditrans(D),denotes_aux(C),denotes_do(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_intrans(D),denotes_main(C),denotes_rise(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_trans(D),denotes_main(C),denotes_border(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_trans(D),denotes_main(C),denotes_contain(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_intrans(D),denotes_main(C),denotes_drain(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_trans(D),denotes_main(C),denotes_exceed(A).
verb_type(A,B):-'denotes_+'(C,D,B),denotes_intrans(D),denotes_main(C),denotes_flow(A).
adverb(A):-denotes_yesterday(A).
adverb(A):-denotes_tomorrow(A).
