
'denotes_$VAR'(f).
'denotes_.'(g,g,g).
'denotes_.'(g,e,g).
'denotes_.'(e,g,g).
'denotes_.'(e,e,g).
'denotes_.'(g,f,i).
'denotes_.'(e,f,i).
'denotes_.'(g,i,i).
'denotes_.'(e,i,i).
'denotes_.'(f,g,i).
'denotes_.'(f,e,i).
'denotes_.'(f,f,i).
'denotes_.'(f,i,i).
'denotes_.'(i,g,i).
'denotes_.'(i,e,i).
'denotes_.'(i,f,i).
'denotes_.'(i,i,i).
'denotes_[]'(e).
